### ISSUE TITLE
Replace the gregorian package

### ISSUE THREAD

**Issue by ThomasThelen** [zizroc/villager#80]
gregorian isn't on cran an we can't submit until it is-so let's replace it with lubridate

**Comment by zizroc** [comment]
Let's just drop this. Having dates doesn't presently add value to the package and it's actually opposing generalization: it's a holdover from when we were thinking about exogenous drivers of change from the climate, and it imposes a calendar system that would have been totally alien to Maya. We can just do time steps with arbitrary labels -- days by default (because of how rates are presently entered), but could be anything. Also in case someone wants to subclass in a way we're not predicting. Why limit? In the future, we can write a few functions to reconstruct Mayan/Gregorian/Julian calendar dates from the output days.

**Comment by ThomasThelen** [comment]
Done in 014869bdc760f08601ccfcde71858a1c3a75f738
